### PR TITLE
add german media (#23)

### PR DESCRIPTION
**Pull request by schochastics**

### CODE REVIEW

**Comment by schochastics** [comment]
@JBGruber  there are many articles at "Der Spiegel" that do not seem to have an author. 

When I run
```r
rss_url <- "https://www.spiegel.de/schlagzeilen/index.rss"
tst <- paperboy::pb_deliver(rss_url)
tst
```

then the column author has "DER SPIEGEL" added for those without author (and sometimes also when there actually is an author). I verified that `pb_deliver.spiegel.de()` has an empty author field. Which function does add "DER SPIEGEL"?

**Comment by schochastics** [comment]
ugh nvm, I guess the function should actually be called `pb_deliver_paper.spiegel.de()`?

**Comment by JBGruber** [comment]
The function actually needs to be named `pb_deliver_paper.spiegel_de`. I wrote the confusingly named `paperboy:::classify("spiegel.de")`, if you're in doubt. I also had a look at the issue that most bylines have DER SPIEGEL. I took the info from a different part of the page and it seems that is simply what they are adding. (while on it I also saw an easier/potentially more robust way to find the headline)

**Comment by schochastics** [comment]
Thanks! Had a bit of a merge nightmare but gonna test both bild and spiegel thoroughly now before moving on

**Comment by schochastics** [comment]
@JBGruber So this got a bit out of hand. At GESIS, we have a webtracking project and one thing led to another and I got a list of the 200 most visited German news websites that we need a scraper for. This pull request is now a little more than the top 100 but I ran out of steam. For now, I hope this does not blow the package out of proportions. Happy to fix anything you think might need fixing.

**Comment by JBGruber** [comment]
Thank you, that's fantastic! I'll check them out this week. Don't forget to add yourself to the description :wink:

**Pull request merged**
